---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grok-pvc
  namespace: work
spec:
  storageClassName: managed-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
