apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-nfs-storage
  namespace: monitoring
  labels:
    type: nfs
spec:
  storageClassName: managed-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.22.252
    path: "/mnt/nfs/grafana-storage"